---
- name: allow 25
  iptables:
    action: insert
    chain: INPUT
    destination_port: 25
    protocol: tcp
    jump: ACCEPT
- name: allow 110
  iptables:
    action: insert
    chain: INPUT
    destination_port: 110
    protocol: tcp
    jump: ACCEPT
- name: allow 143
  iptables:
    action: insert
    chain: INPUT
    destination_port: 143
    protocol: tcp
    jump: ACCEPT

